### ISSUE TITLE
スクリーンショット置き場

### ISSUE THREAD

**Issue by s-sasaki-0529** [Sa2Knight/pullkan#14]

**Comment by Sa2Knight** [comment]
<img width="960" alt="pullkan" src="https://user-images.githubusercontent.com/16274215/108626920-06a00980-7496-11eb-8e14-e412c3962469.png">

**Comment by Sa2Knight** [comment]
v1.1.0

![0b372835a54a4a6bd6431270e8e83480f3a9da91-2021-07-02T16_33_37Z](https://user-images.githubusercontent.com/16274215/124304516-c288e800-db9e-11eb-89cb-cbef5ff992a8.png)
